PIN_ROOT ?= /home/george/adv-ca/pin-3.23-98579-gb15ab7903-gcc-linux/

CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
